In [1]:
#vector is a tuple of one or more values called scalars.
#Vector represents a point or coordinate in an n-dimensional space, where n is the no.of dimensions.
#We can represet vector as a column, row or matrix.
# A simple vector can be represented as v = (v1,v2,v3) 

# Defining a vector

In [2]:
import numpy as np
#define vector
v1 = np.array([1,2,3])
v2 = np.linspace(1,10).reshape(10,5)

#print(v1,v2)
#print(type(v1))
print(np.shape(v1))
print(np.shape(v2))

(3,)
(10, 5)


In [3]:
a = np.array([1,2,3])
b= np.array([1,2,3])
print("----arithmetic vector operations --------")
print("a+b => ",a+b)
print("a-b => ",a-b)
print("a*b => ",a*b)
print("a/b => ",a/b )

----arithmetic vector operations --------
a+b =>  [2 4 6]
a-b =>  [0 0 0]
a*b =>  [1 4 9]
a/b =>  [1. 1. 1.]


# Vector dot product

In [4]:
print("dot product (a.b) => ",a.dot(b))

dot product (a.b) =>  14


# Vector - Scalar multiplication

In [5]:
#c = s * v , where s is scalar and v is vector, so we can describe this notation as below
#c = sv
#c = (s*v1,s*v2,s*v3)  or put another way c[0]= v[0]*s ,c[1]=v[1]*s , c[2]=v[2]*s
#define scalar
s = 0.5
c = s * a
print(c)

[0.5 1.  1.5]


# Vector Norm

In [37]:
from numpy.linalg import norm
from numpy import array
import math 
from numpy import inf

#define vector
a= array([1,2,3])

#calcuate norm
l1 = norm(a,ord=1)
print(l1)

6.0


In [38]:
l2 = norm(a,ord=2)
print(l2)

def_l2 = norm(a)
print(def_l2)

v = math.sqrt((1**2)+(2**2)+(3**2))
print(v)

3.7416573867739413
3.7416573867739413
3.7416573867739413


In [39]:
max_norm = norm(a,ord=inf)
print(max_norm)

3.0


In [40]:
norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

# Matrix Operations

In [42]:
from numpy import array

a = array([[1,2],
           [3,4],
           [5,6]])

b= array([[1,2],[3,4]])

In [47]:
c = a.dot(b)
print(c)
d = a @ b
print(d)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


# Trailgular matrix

In [49]:
from numpy import tril
from numpy import triu
M = array([[1,2,3],[1,2,3],[1,2,3]])
print(M)

#lower triangular matrix
lower = tril(M)

#upper triangular matrix
upper = triu(M)

print(lower)
print(upper)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


# Diagonal Matrix


In [58]:
from numpy import diag

diag1= diag(M)
print(diag1)
D = diag(diag1)
print(D)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Identity Matrix

In [57]:
from numpy import identity
I = identity(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Sparse Matrix

In [26]:
l =[i for i in range(0,20)]
first_order = l[0::2]
sencond_order = l[1::2]
co_ordinate_list = list(zip(first_order,sencond_order))

In [23]:
print(first_order,sencond_order)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [28]:
print(co_ordinate_list)
type(co_ordinate_list)
#Co-oridnate list is one way to hold and store sparse matrix 

[(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17), (18, 19)]


list

In [29]:
from numpy import array
from scipy.sparse import csr_matrix

#Create Dense matrix
A = array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]
])

In [33]:
print(A)

#Convert to sparse matrix
S = csr_matrix(A)
print(S)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [35]:
#Reconstruct to Dense
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [44]:
from numpy import count_nonzero
nonzero_size = count_nonzero(A)
arr_size = A.size
print(nonzero_size,arr_size)
sparsity =1.0 - (nonzero_size/arr_size)
print(sparsity)

5 18
0.7222222222222222


# Tensors & Tensors Arithmetic

In [45]:
from numpy import array
T = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]])

In [51]:
print(T.shape)
print(T.size)

(3, 3, 3)
27


# Tensor Arithmetic 

In [52]:
from numpy import array

#define first tensor
t1 = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]])

t2 = T = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]])

In [58]:
#tensor addition
t3 = t1 + t2
print(t3)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [59]:
#tensor substraction
t4 = t1 - t2
print(t4)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [60]:
#tensor hadamard product
t5 = t1 * t2 
print(t5)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


In [61]:
#tensor division

t6 = t1 / t2
print(t6)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [66]:
#Tensor product

from numpy import array
from numpy import tensordot

#define first vector
A = array([1,2])

#define 2nd vector
B = array([3,4])

#calcualate tensor product
C = tensordot(A,B,axes=0)
print(C)

D = tensordot(A,B,axes =1)
print(D)

[[3 4]
 [6 8]]
11


# Matrix Decomposition

In [12]:
#LU decomposition
from numpy import array
from scipy.linalg import lu
from scipy.linalg import qr

A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(A)
P, L , U = lu(A)
print(P)
print(L)
print(U)

#Reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
# QR decomposition - Not limited to square matrices with n*m dimenstions.
# define rectangular matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)
# factorize
Q, R = qr(A)

print(Q)
print(R)

# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Cholesky Decomposition

In [21]:
from numpy.linalg import cholesky

#Define symmetic matrix - means (A= L.LT)
A = array([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
print(A)

#factorize
L = cholesky(A)

print(L)

#Reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# Eigen Decomposition

In [34]:
from numpy import array
from numpy.linalg import eig
from numpy.linalg import inv
from numpy import diag
#Define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(A)

#Factorize

values,vectors = eig(A)
print('\n',values)
print('\n',vectors)

#confrim first eigenvector
B = A.dot(vectors[:,0])
print('\n',B)
C = vectors[:,0] * values[0]
print('\n',C)

#Reconsturct a matrix

#Create matrix from eigen vectors
Q = vectors
#Create inverse of eigenvector matrix
R = inv(Q)
print(R)
#create diagonal matrix from eigenvalues

L = diag(values)
print(L)

#Reconstruct matrix to the original matrix
B = Q.dot(L).dot(R)

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

 [ -3.73863537  -8.46653421 -13.19443305]

 [ -3.73863537  -8.46653421 -13.19443305]
[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
