In [1]:
#vector is a tuple of one or more values called scalars.
#Vector represents a point or coordinate in an n-dimensional space, where n is the no.of dimensions.
#We can represet vector as a column, row or matrix.
# A simple vector can be represented as v = (v1,v2,v3) 

# Defining a vector

In [2]:
import numpy as np
#define vector
v1 = np.array([1,2,3])
v2 = np.linspace(1,10).reshape(10,5)

#print(v1,v2)
#print(type(v1))
print(np.shape(v1))
print(np.shape(v2))

(3,)
(10, 5)


In [3]:
a = np.array([1,2,3])
b= np.array([1,2,3])
print("----arithmetic vector operations --------")
print("a+b => ",a+b)
print("a-b => ",a-b)
print("a*b => ",a*b)
print("a/b => ",a/b )

----arithmetic vector operations --------
a+b =>  [2 4 6]
a-b =>  [0 0 0]
a*b =>  [1 4 9]
a/b =>  [1. 1. 1.]


# Vector dot product

In [4]:
print("dot product (a.b) => ",a.dot(b))

dot product (a.b) =>  14


# Vector - Scalar multiplication

In [5]:
#c = s * v , where s is scalar and v is vector, so we can describe this notation as below
#c = sv
#c = (s*v1,s*v2,s*v3)  or put another way c[0]= v[0]*s ,c[1]=v[1]*s , c[2]=v[2]*s
#define scalar
s = 0.5
c = s * a
print(c)

[0.5 1.  1.5]


# Vector Norm

In [37]:
from numpy.linalg import norm
from numpy import array
import math 
from numpy import inf

#define vector
a= array([1,2,3])

#calcuate norm
l1 = norm(a,ord=1)
print(l1)

6.0


In [38]:
l2 = norm(a,ord=2)
print(l2)

def_l2 = norm(a)
print(def_l2)

v = math.sqrt((1**2)+(2**2)+(3**2))
print(v)

3.7416573867739413
3.7416573867739413
3.7416573867739413


In [39]:
max_norm = norm(a,ord=inf)
print(max_norm)

3.0


In [40]:
norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

# Matrix Operations

In [42]:
from numpy import array

a = array([[1,2],
           [3,4],
           [5,6]])

b= array([[1,2],[3,4]])

In [47]:
c = a.dot(b)
print(c)
d = a @ b
print(d)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


# Trailgular matrix

In [49]:
from numpy import tril
from numpy import triu
M = array([[1,2,3],[1,2,3],[1,2,3]])
print(M)

#lower triangular matrix
lower = tril(M)

#upper triangular matrix
upper = triu(M)

print(lower)
print(upper)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


# Diagonal Matrix


In [53]:
from numpy import diag

diag1= diag(M)
print(diag1)
D = diag(diag1)
print(D)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Identity Matrix

In [56]:
from numpy import identity
I = identity(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
